Updates maintenance/license year to 2023
hassio-addons/addon-tailscale pull request #130
Opened 2023-01-07 21:45 UTC by lmagyar

# Proposed Changes

Documentation fix

2023-02-11 20:21 UTC, lmagyar commented
Not stale, waiting for review/merge...

2023-03-14 08:56 UTC, lmagyar commented
Not stale, waiting for review/merge...

2023-03-25 18:15 UTC, frenck requested changes

2023-03-25 18:15 UTC, frenck commented on tailscale/DOCS.md
> +
Unrelated changes to this PR

2023-03-25 20:46 UTC, frenck requested changes
Setting review status correctly

2023-03-25 20:59 UTC, frenck commented
superseded by #155

2023-03-25 20:59 UTC, closed without merging