Minor bugfixes
hassio-addons/addon-tailscale pull request #131
Opened 2023-01-07 21:50 UTC by lmagyar

PR #130 precedes this PR

# Proposed Changes

See commits:
- fix: jq: error (at <stdin>:1): Cannot iterate over null (null)
- fix: unnecessary "true" or "false" log entry

2023-02-11 20:20 UTC, lmagyar commented
Not stale, waiting for review/merge...

2023-03-14 08:56 UTC, lmagyar commented
Not stale, waiting for review/merge...

2023-03-25 20:42 UTC, frenck requested changes

2023-03-25 20:42 UTC, frenck commented on LICENSE.md
> +Copyright (c) 2021-2023 Franck Nijhof
Unrelated change for this PR

2023-03-25 20:42 UTC, frenck commented on tailscale/rootfs/etc/services.d/tailscaled/post
> +tags=$(bashio::config "tags//[] | join(\",\")" "")
Nice 👍

2023-03-26 09:21 UTC, frenck commented
Rebased the PR, and removed the unrelated documentation changes.

2023-03-26 09:26 UTC, frenck approved these changes
Thanks, @lmagyar 👍 

../Frenck

2023-03-26 09:26 UTC, merged