Bump base image to 13.0.1
hassio-addons/addon-tailscale pull request #132
Opened 2023-01-07 21:52 UTC by lmagyar

PR #130 and #131 precedes this PR

# Proposed Changes

Bump base image to 13.0.1

2023-02-18 15:54 UTC, lmagyar commented
Not stale, still relevant.

2023-03-25 18:19 UTC, frenck requested changes

2023-03-25 18:19 UTC, frenck commented on LICENSE.md
> +Copyright (c) 2021-2023 Franck Nijhof
This PR has unrelated changes to the base image bump (like this one, but many more).

2023-03-25 20:26 UTC, frenck commented
superseded by #153

2023-03-25 20:26 UTC, closed without merging