Bump Tailscale to 1.34.2
hassio-addons/addon-tailscale pull request #133
Opened 2023-01-07 21:54 UTC by lmagyar

Replaces PR #127

PR #130, #131 and #132 precedes this PR

# Proposed Changes

Bump Tailscale to 1.34.2

2023-01-26 03:11 UTC, HazWard commented
@lmagyar I think you need to add a label to the PR in for the GitHub Actions to pass.

2023-01-26 07:30 UTC, lmagyar commented
> @lmagyar I think you need to add a label to the PR in for the GitHub Actions to pass.

Only the repo owners can add labels.

2023-01-27 02:12 UTC, HazWard commented
> Only the repo owners can add labels.

Ah that's unfortunate, there's not much activity.

2023-02-01 19:41 UTC, Migelo commented
Dear @frenck and @jeffothy . I think this pull request seems fine and I'd love to get the newest version of Tailscale running on my HA instance. Can you please have a look at this PR?

2023-03-10 22:04 UTC, jaws35smith commented
Hi @frenck and/or @jeffothy.  Can you please have a look at this PR?

2023-03-13 14:23 UTC, BartoszPierzchlewiczMacrix commented
Hi, what is the problem with accepting this pull request?
People are contributing, discussing, but no answers from "owners".
lmagyar is so patient with continuously updating PR and answering questions.
What is wrong with this PR? Is there anything to improve?
@frenck @jeffothy please speak up.

2023-03-14 17:57 UTC, jeffothy commented
> > @lmagyar I think you need to add a label to the PR in for the GitHub Actions to pass.
> 
> Only the repo owners can add labels.




> Hi @frenck and/or @jeffothy. Can you please have a look at this PR?




> Hi, what is the problem with accepting this pull request? People are contributing, discussing, but no answers from "owners". lmagyar is so patient with continuously updating PR and answering questions. What is wrong with this PR? Is there anything to improve? @frenck @jeffothy please speak up.




> Could it be that it is not in their interest to support tailscale officially, as it directly undermines one of the main selling points of Home Assistant Cloud?

Unfortunately, I am not a codeowner here nor a maintainer on this repository.
However, I did contribute the most recently merged upgrade bump PR https://github.com/hassio-addons/addon-tailscale/pull/108
Based on that PR and the review of a related dep bump PR https://github.com/hassio-addons/addon-tailscale/pull/109 by Franck, perhaps I can make a couple suggestions here:
1. Based on a historical [review comment](https://github.com/hassio-addons/addon-tailscale/pull/108#discussion_r962181872), I would say the preference is to only make required and related changes in the Upgrade PR. I suggest the removal of the unnecessary changes here in the PR:
    - Are the base image bumps required in this PR? (can they be delivered separately?)
    - What about the docs and scripts minor modifications?
2. The fact that there is a [vulnerability](https://github.com/hassio-addons/addon-tailscale/issues/124) in the current addon version provides some good justification for the PR, and should probably be mentioned in the description.

2023-03-15 21:08 UTC, lmagyar commented
> - Are the base image bumps required in this PR? (can they be delivered separately?)
> - What about the docs and scripts minor modifications?

You're right.

As I remember, due to some version changes the current master branch 6be6bff0fb894fd9f8adc441663c086c0ba4f4b6 can't be built, so some Dockerfile and base image changes required before doing anything, so that's why some PR precedes this. I thought this way I keep this PR at least build-able.

And those required commits has their own PR, so my plan was to rebase this PR after those PRs are merged.

2023-03-19 04:18 UTC, austinliuu commented
Would like to see the PR got merged as the current add on is pretty out of date

2023-03-23 05:52 UTC, DezzyMelb commented
Please merge. There are even newer versions available now so this merge is getting a little outdated.

2023-03-23 09:49 UTC, lmagyar commented
It's not outdated, I regularly push new commits to this PR with the latest Tailscale releases when I update my fork.

2023-03-23 14:19 UTC, Migelo commented
I asked @frenck on Discord about and he said "I get to it when I get to it". 
@lmagyar is there a way for me to use your branch in my Home Assistant Operating System deployment?

2023-03-23 16:15 UTC, lmagyar commented
> is there a way for me to use your branch in my Home Assistant Operating System deployment?

Yes, use my forks (they are fully functional drop-in replacements, images pre-built and stored by Github):
https://github.com/lmagyar/homeassistant-addon-tailscale
https://github.com/lmagyar/homeassistant-addon-tailscale-funnel (it has additional support for the new Tailscale Funnel feature ([deatils](https://github.com/lmagyar/homeassistant-addon-tailscale-funnel/blob/main/tailscale/DOCS.md#tailscale-funnel-prerequisites)))

2023-03-24 01:13 UTC, DezzyMelb commented
> It's not outdated, I regularly push new commits to this PR with the latest Tailscale releases when I update my fork.

Not stale in that sense. You cannot keep chasing your tail when things are not getting merged. I assume you've been trying to merge these updates for some time.

2023-03-24 02:22 UTC, austinliuu commented
> > It's not outdated, I regularly push new commits to this PR with the latest Tailscale releases when I update my fork.
> 
> Not stale in that sense. You cannot keep chasing your tail when things are not getting merged. I assume you've been trying to merge these updates for some time.

@frenck

2023-03-25 20:43 UTC, frenck requested changes
The PR is full of unrelated changes.

2023-03-25 20:57 UTC, frenck commented
superseded by #152

2023-03-25 20:57 UTC, closed without merging