Fix Proxy and Funnel functionality when they are disabled
hassio-addons/addon-tailscale pull request #273
Opened 2023-10-17 15:24 UTC by lmagyar

# Proposed Changes

Nuke `tailscale serve` and `tailscale funnel` configs on startup (better nuke I think, who knows what change will come later).

This can be done only after `tailscale up` is ready. Then we have to stop the add-on if deleting the configs wasn't successful (small chance).

## Related Issues

fixes #272

2023-10-17 15:26 UTC, frenck requested changes
To fix the referenced issue, we also need to change the defaults.

2023-10-17 15:28 UTC, lmagyar commented
> To fix the referenced issue, we also need to change the defaults.

And rewrite the DOCS, translate.yaml, a lot of mentioning of the proxy functionality... I will do that a few hours later, but now I have to stand up from my keyboard...

2023-10-17 19:02 UTC, lmagyar commented
I've made both proxy and funnel by default disabled. Basic manual tests are done on my real rPI-s, enabling/disabling them, everything seems to be OK.

Positive side effect: after install the add-on can be started immediately, no HA reverse proxy or add-on config required.

2023-10-18 06:02 UTC, lmagyar commented
And from now on when proxy and funnel service can't start, this is not a notice, this is an error.

2023-10-19 20:31 UTC, frenck commented
[1e63fdb](https://github.com/hassio-addons/addon-tailscale/pull/273/commits/1e63fdb1df3856124a6e9360c1a606c32faeaa3d)

This is not related to this PR. Please move it.

2023-10-19 20:31 UTC, frenck requested changes
Wrong button. See above comment.

2023-10-19 20:35 UTC, lmagyar commented
OK, but it makes really sense. Will make a PR based on this PR.

2023-10-19 22:16 UTC, lmagyar commented
Finally moved all non port related code into this PR, because now it's much clearer which service does what.
Now both are ready to review.

2023-10-22 16:03 UTC, frenck commented on tailscale/rootfs/etc/s6-overlay/s6-rc.d/funnel/run
> +    bashio::exit.nok
Wouldn't raising an `nok` on the service run cause the service to restart?

2023-10-22 16:23 UTC, lmagyar commented on tailscale/rootfs/etc/s6-overlay/s6-rc.d/funnel/run
> +    bashio::exit.nok
Yes, that was my goal, like in case of the proxy: if we can't reset the config, do not let `tailscale up` to run, because that will expose HA to funnel even when the user do not want it anymore. Sadly we can test the current proxy/funnel config only after `tailscale up` was successful.

2023-10-22 16:26 UTC, frenck approved these changes
Thanks, @lmagyar 👍 

../Frenck

2023-10-22 16:26 UTC, merged