Fix local subnet protection
hassio-addons/addon-tailscale pull request #275
Opened 2023-10-17 19:41 UTC by lmagyar

***Based on #273, no merge conflict only after that is merged!***

## Proposed Changes

Fixes a logical bug in #201: That PR protected the ***advertised*** subnets, what was originally identical with the ***local*** subnets, but after the advertised subnets are user configurable, I think the subnet protection logic should always protect ***local*** subnets, independently of what users configured to be advertised. Because collisions will be between local and accepted routes not between advertised and accepted.

**Note:** There is another possible improvement, but that is not addressed by this PR: We protect subnet domains, maybe should only protect HA's local IPs only. But I'm not sure whether it solves or creates more problems. Until there is some concrete need for it, I prefer not to modify the current logic.

## Related Issues

2023-10-18 13:17 UTC, frenck requested changes
There are unrelated commits in this PR, please remove them.

2023-10-20 15:46 UTC, lmagyar commented
Rebased, to prevent merge conflicts.

2023-10-20 15:59 UTC, frenck commented
> Rebased, to prevent merge conflicts.

Can you please remove the unrelated commits? As per request above. Rebase only related changes please 👍

2023-10-20 16:08 UTC, lmagyar commented
And you are right again... (no merge conflict with other proxy modification in either way).
Marking ready to review.

2023-10-22 15:30 UTC, frenck approved these changes
Nice! Thanks, @lmagyar 👍 

../Frenck

2023-10-22 15:30 UTC, merged