Make auth-key configurable
hassio-addons/addon-tailscale pull request #279
Opened 2023-10-21 15:02 UTC by lmagyar

## Note: the unrelated changes are already in PR #274, this PR needs to be rebased after that is merged.

# Proposed Changes

Adds an optional `auth_key` to the config to be used in `tailscale up`

***Note:*** There is a tailscale bug (https://github.com/tailscale/tailscale/issues/9715) that makes non-reusable Auth keys unusable/broken (in general, not only in this add-on), so please test it with reusable Auth keys!

## Related Issues

fixes #266

2023-10-22 15:28 UTC, frenck requested changes
> Note: the unrelated changes are already in PR https://github.com/hassio-addons/addon-tailscale/pull/274, this PR needs to be rebased after that is merged.

Don't stack things, it make things impossible to review, super messy and hard to move forward (without any reason actually). Please rebase this PR and only pick what is needed.

../Frenck

2023-10-22 15:51 UTC, lmagyar commented
Rebased, ready to review, but now other PRs will have merge conflicts.

2023-10-22 17:08 UTC, frenck commented
I miss the motivation for "Why" we would add this feature?

This is also missing in the linked issue.

../Frenck

2023-11-22 10:38 UTC, lmagyar commented
Closing, as original issue can be closed also.

2023-11-22 10:38 UTC, closed without merging